### ISSUE TITLE
Modular Python Structure

### ISSUE THREAD

**Issue by matthewelse** [0xc0170/project_generator#38]
We can potentially make all of the core in this repository into a proper Python module with a proper setup script etc. this will probably help with testing as currently I have to add the root directory of this repo to Python path in order to import the various classes etc.

**Comment by 0xc0170** [comment]
This task is now in progress :+1:

**Comment by 0xc0170** [comment]
Got a branch, https://github.com/0xc0170/project_generator/tree/dev_packagify. IAR and uVision seems to be fine at the moment

**Comment by 0xc0170** [comment]
Landed !
