### ISSUE TITLE
Automagically create yaml files for a given directory

### ISSUE THREAD

**Issue by sg-** [0xc0170/project_generator#51]
There should be a command that creates a yaml file for the directory. There could also be standard settings ie: debug, no optimizations, etc. so all developers need to do is edit a file, not create and maintain it.

**Comment by 0xc0170** [comment]
How would you specify which directory? All directories within the path where was project_generator executed ?

**Comment by sg-** [comment]
'''
project_generator.py -c <path with source>
'''

**Comment by 0xc0170** [comment]
Looks good, will look at this.

**Comment by matthewelse** [comment]
Perhaps we could use argparse's subcommand feature for this sort of thing e.g.

`project_generator start_project xyz` or `project_generator init xyz`

**Comment by 0xc0170** [comment]
That init command is a good idea. But how would be the tree transformed to records? One big yaml file with all files in it?

**Comment by sg-** [comment]
I think yaml per directory inside of /src. Kinda like a submodule would be placed.

**Comment by 0xc0170** [comment]
v0.4 was published. I'll close this as this functionality is there. If any new features regarding init command, any missing bits, we can create a new issue for it. THanks @sg- for reporting and helping with this
