### ISSUE TITLE
Add more debug messages

### ISSUE THREAD

**Issue by 0xc0170** [0xc0170/project_generator#66]
I imagine that once something does not go correctly with the project_generator, a user just enables debug messages, to be able tofind out why it fails or behaves incorrectly.

If it's a bug, the report within debug level can be provided in the issue report.

**Comment by matthewelse** [comment]
Is it currently using `logging`, the library built in to Python - this could simplify this issue

**Comment by matthewelse** [comment]
This issue was fixed by #68

**Comment by 0xc0170** [comment]
#102 was merged , which prints project dictionary and mcu definitions when debug logging is set
